site_name: UAGC DX Team Hub
site_description: Central home for every repeatable task that keeps uagc.edu running
site_url: https://uagc-dx-documentation.readthedocs.io/
repo_url: https://github.com/omac049/uagc-dx-documentation
repo_name: omac049/uagc-dx-documentation
edit_uri: edit/main/docs/
site_author: UAGC DX Team
copyright: Copyright &copy; 2025 UAGC Digital Experience Team

theme:
  name: material
  features:
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky  # Keep tabs visible when scrolling
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - navigation.instant  # Fast navigation between pages
    - navigation.prune    # Reduce size of sidebar to relevant items only
    - navigation.expand   # Expand all collapsible sections
    - navigation.breadcrumb  # Enable breadcrumbs
    - toc.follow          # Follow table of contents while scrolling
    - toc.integrate       # Integrate table of contents into navigation
    
    # Search
    - search.highlight
    - search.share
    - search.suggest
    - search.highlight    # Highlight search terms on result page
    
    # Content
    - content.tabs.link
    - content.code.copy
    - content.code.annotate # Enables code annotations
    - content.action.edit
    - content.action.view
    - content.tooltips      # Show tooltips on hover
    - content.footer        # Add footer to each page
    
    # Announce bar support
    - announce.dismiss
    
    # Header
    - header.autohide      # Hide header when scrolling down
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/notebook
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      default: material/tag
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
    annotation: material/plus-circle
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  static_templates:
    - 404.html

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - javascripts/navigation-fix.js  # Add this first for priority loading
  - javascripts/icons-fix.js
  - javascripts/version-fix.js
  - javascripts/mike-version-fix.js
  - javascripts/sidebar-enhance.js
  - javascripts/extra.js
  - javascripts/spa-navigation.js
  - overrides/assets/javascripts/latest-redirect.js

# Plugins
plugins:
  - search
  - tags
  # - social  # Temporarily disabled due to dependency issues
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - glightbox:
      effect: zoom
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
  - redirects:
      redirect_maps:
        'old/page.md': 'guides/getting-started.md'
        'legacy/index.md': 'index.md'
        'latest/index.md': 'index.md'
  - awesome-pages:
      collapse_single_pages: false
      strict: false
  - macros:
      module_name: main

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "pymdownx.superfences.fence_code_format"
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - tables
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
      permalink_title: Anchor link to this section
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - def_list
  - pymdownx.emoji
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - footnotes
  - md_in_html

# Navigation structure
nav:
  - Home:
    - Welcome: index.md
    - How to Use This Documentation: how-to-use.md
    - Why This Documentation Exists: why-this-exists.md
    - Recent Updates: recent-updates.md
  - Getting Started:
    - Understanding the DX & Enrollment Funnel: digital-experience-enrollment-funnel.md
    - Onboarding Guide: guides/getting-started.md
    - Daily Operations: day-to-day-ops.md
    - Common Tasks: common-tasks.md
    - Team Roles & Responsibilities: who-does-what.md
  - QA & Development:
    - Development Standards & Processes:
      - Drupal Coding Standards: guides/drupal-standards.md
      - General Development Workflows: development-workflows.md
      - Performance & Core Web Vitals: guides/performance-web-vitals.md
    - QA Processes:
      - QA Smoke Test: guides/qa-smoke-test.md
      - Accessibility Checking: guides/accessibility.md
    - Page Management:
      - Page Changes (Add/Remove/Redirect): guides/page-changes.md
      - Content Updates: content-updates.md
    - Release Management:
      - Release & Incident Procedure: guides/release-incident.md
  - Tracking & Analytics:
    - Analytics Strategy & Governance:
      - Overview: analytics-standards.md
      - KPIs for Enrollment Funnel: enrollment-funnel-kpis.md
    - Implementation Details:
      - GA4 Setup & Event Tracking: ga4-setup-event-tracking.md
      - GTM Configuration & dataLayer: gtm-configuration-datalayer.md
      - BigQuery Pipelines: guides/bigquery.md
      - Lead API & Salesforce Data Flow: lead-api-salesforce-integration.md
    - Testing & Optimization:
      - Optimizely Tests: guides/optimizely-tests.md
      - A/B Testing: ab-testing.md
    - Privacy, Consent & Data:
      - Privacy & Consent: guides/privacy-consent.md
      - Cookie Organization & Management: cookie-organization.md
      - User Consent Procedures: user-consent-procedures.md
  - Web Guidelines:
    - SEO:
      - SEO Hygiene: guides/seo-hygiene.md
      - SEO Redirect Decision Tree: guides/seo-redirects.md
      - Canonical Links & URL Taxonomy: canonical-links-url-taxonomy.md
    - Accessibility:
      - WCAG Compliance: wcag-compliance.md
      - Accessibility Checklist: accessibility-checklist.md
    - Content:
      - Writing Guidelines: guides/content-standards.md
      - Content Templates: content-templates.md
    - UI/UX:
      - Best Practices & Component Library: ui-ux-best-practices.md
  - References & Tools:
    - Asana Workflow: asana.md
    - Glossary: guides/glossary.md
    - Site Map: sitemap.md
    - RFI Form: request-information-form.md
    - Documentation Workflow: documentation-workflow.md
    - Growth Roadmap: growth-roadmap.md
    - Keyboard Shortcuts: keyboard_shortcuts.md
    - Draft Documents:
      - Documentation Outline: outline-draft/outline.md
  - Not Found: 404.md

# Extra features
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
      github: GitHub
  version:
    provider: mike
    default: latest
    select_enabled: true
    select_label: "Version"
  analytics:
    provider: google
    property: 'G-XXXXXXXXXX'  # Replace with your actual Google Analytics property ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/omac049/uagc-dx-documentation/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">creating an issue</a>.
  # Shortcuts for keyboard navigation (Alt+key)
  keyboard:
    h: "/"  # Home
    n: "!next"  # Next page
    p: "!prev"  # Previous page
    s: "/search.html"  # Search
    t: "#"  # Back to top
  # Announcement banner
  announce:
    content: Updates are in progress! Documentation Day is scheduled for <strong>June 15, 2025</strong>
  # Page status
  status:
    new: 
      - "getting-started"
    experimental:
      - "advanced-concepts"
    deprecated:
      - "legacy-guide"
  
# Configuration for 404 page
use_directory_urls: true
